### ISSUE TITLE
More documentation on creating commands with parameter

### ISSUE THREAD

**Issue by vikbez** [Salandora/octoprint-customControl#1]
I'd wanted to create a slider that sends a command to the printer with like G92 {param}

I've done something like that:

![](http://www.cjoint.com/doc/16_01/FAdl0pUqHxt_Capture-d%E2%80%99e%CC%81cran-2016-01-03-a%CC%80-12.51.50.png)

The problem is that the command sent is G92 {height}
How do I set the parameter in the command line to be replaced by the parameter from the input slider ?

thanks

**Comment by Salandora** [comment]
You need change G92 {height} to G92 Z%(height)s
You can think of this Plugin as custom controls only config editor.
So you basically apply the same rules as if you would do in config.yaml (http://docs.octoprint.org/en/master/features/custom_controls.html#controls)

**Comment by vikbez** [comment]
Thanks for the documentation link !
You should add it to the README.md

**Comment by mvasilakis** [comment]
For input does it ask for user input? 
For instance can I make a button to ask user to enter new E-Step as Name "step". Say user enters 285. Then feed the 285 into the following command?
M92 E%(steps)
