### ISSUE TITLE
Controls on the Terminal tab instead of the Control tab

### ISSUE THREAD

**Issue by b-morgan** [Salandora/octoprint-customControl#11]
I have created a collection of custom controls to change E-steps, Z-offset, load, save, and show settings and all works well except for one minor annoyance. When I click "Show Settings" I have to then switch to the Terminal tab to view the results. Ideally, all of these controls would be better if they were located on the Terminal tab instead of the Control tab.

Would it be possible to add functionality to choose which tab the custom controls are on? If so, would it be possible to select on a per-control basis?

**Comment by Salandora** [comment]
Sadly no,t inside this Plugin, because the custom controls are a core feature of OctoPrint itself.
This is only an Editor to easily add,edit,remove,arrange controls.
So your question/feature request would be better at @foosel's OctoPrint repository.
