### ISSUE TITLE
Running python script

### ISSUE THREAD

**Issue by Mungbeanz** [Salandora/octoprint-customControl#13]
I was just wanting to run a simple python script that controls some GPIO pins and another that starts some services.

This is what I have done so far:

![capture](https://user-images.githubusercontent.com/33512163/35783778-cb3454dc-0a71-11e8-8c34-a6f44b2698e1.PNG

Is it even possible to run python scripts from this plugin.  I know it can be done in the config.yaml but didn't really want to delve into messing around with that.

**Comment by Salandora** [comment]
Sorry but OctoPrints custom controls only send GCODE commands to the printer.
What you need are the system commands.
