### ISSUE TITLE
System command

### ISSUE THREAD

**Issue by oscarmorrison** [Salandora/octoprint-customControl#17]
Hey @Salandora great work.

I need a button that run a system command. eg.

Button: `Turn on printer`
System command: `curl -X POST https://maker.ifttt.com/trigger/turn_off_3d_printer/with/key/mykeyhere`

Any ideas how I can do that

**Comment by Salandora** [comment]
Sadly not with the customControls, what you're looking for are the systemCommands :-)

**Comment by kaweksl** [comment]
Would be nice to have possibility to run system commands from Controls tab. SystemCommands plugin places its commands in menu bar as drop-down with is inconvenient.

Now I'm using combination with Gcode System Commands but it looks like nasty workaround and i can't provide any input arguments.

**Comment by Salandora** [comment]
Well this would need to be implemented in OctoPrint itself.
This little plugin here ist just a helper to not mess around with the config.yaml file.
The control tab system is OctoPrint Core functionality.
