### ISSUE TITLE
Possibility to run system commands

### ISSUE THREAD

**Issue by svh1985** [Salandora/octoprint-customControl#2]
Hi,

I would like to add some buttons to control my webcam.
At this point I've added them in the system menu with your other plugin (OctoPrint-SystemCommandEditor) but placing these buttons below the webcam view is a more logic place.
Also, the user input option would be very nice to change the focus point.

This is for example the change focus point command:
uvcdynctrl -v -d video0 --set='Focus (absolute)' 80

To change the focus it must run as a system command.

Is there a way to run these commands via this plugin?

Thanks!

**Comment by Salandora** [comment]
This plugin is only an editor to help you create and manage some custom commands in the control tab.

OctoPrint at the moment doesn't allow to create system commands on the control tab.

You could fork my PanTilt plugin (repository list) and modify it to your needs.
