### ISSUE TITLE
Z offset

### ISSUE THREAD

**Issue by davide70** [Salandora/octoprint-customControl#20]
Hello.
Congratulations and thanks for the useful plugin. I'm not an expert in Linux and Octopi and I need an help. I would like to add a custom control for the Z Offset of my printer. I found this code and I read I can use your plugin so I don't have to edit the config file:
 
controls:
- children:
  - command: M628
    default: ''
    name: Get
    regex: z zero offset value:(?P<offset>\d+(\.\d*))
    template: 'Current: {offset} mm'
    width: '5'
  - command: M628 Z%(offset)s
    input:
    - default: '0.00'
      name: New (mm)
      parameter: offset
      slider: false
    name: Set
    width: '5'
  - command: G28 Z0
    name: Home Z
    width: '2'
  collapsed: true
  layout: horizontal_grid
  name: Adjust Z Offset

Can you tell me how to write this code in your plugin please? Thanks

**Comment by Salandora** [comment]
Hello @davide70,
sorry for the late replay.

My Plugin basically adds an Entry to the settings menu inside of OctoPrint where you can add new Entries, edit existing ones or delete them.

To add a command like the M628 You'll need to open the settings navigate to Custom Control Editor
open the context menu in the green box and create a Container element.

After that open the context menu of the newly created container and add a command button.
You now have to fill in the textboxes with the corresponding values and click confirm.
well an that's it.
You now can create a second button for your M628 Set command (Hint: Use Inputs)

Hope I could help even if it's late. Sorry for that real life is quite busy in the last 2 years or so...

**Comment by Salandora** [comment]
I think this can be closed.
