### ISSUE TITLE
Python3

### ISSUE THREAD

**Issue by zonk0101** [Salandora/octoprint-customControl#30]
The Plugin is not yet Python3 ready - or the tag is missing

**Comment by ciordia9** [comment]
.. just finished migration and noticed this plugin was offline due to environment. Best simple plugin ever. /sigh /ponder

**Comment by Salandora** [comment]
Should have been fixed a long time ago, just never made a proper release for it, should be done now with version 0.2.2 also added the compatibility flag and updated the plugins.octoprint.org page.

Feel free to comment here or open a new ticket if something is not working properly
