### ISSUE TITLE
Bed Visualizer "Update Mesh Now" deletes all buttons in Python 3 Octoprint release

### ISSUE THREAD

**Issue by pediegoivan** [Salandora/octoprint-customControl#37]
When the "Update Mesh Now" button is pressed from the Bed Visualizer Plugin, all the buttons from the Custom Control Editor are deleted.

**Comment by BNWEIN** [comment]
I have also had this same issue.

**Comment by pediegoivan** [comment]
> I have also had this same issue.

The Bed visualizer developer reached out to me last night with a patched version of this firmware that does work as intended.
https://github.com/jneilliii/octoprint-customControl/archive/devel.zip
